apiVersion: v1
kind: Service
metadata:
  name: project-forest-service
  namespace: ${NAMESPACE}
  labels:
    app: project-forest
    environment: ${ENVIRONMENT}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/api/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-unhealthy-threshold: "3"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: project-forest
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: project-forest-metrics
  namespace: ${NAMESPACE}
  labels:
    app: project-forest
    service: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: project-forest
---
apiVersion: v1
kind: Service
metadata:
  name: project-forest-headless
  namespace: ${NAMESPACE}
  labels:
    app: project-forest
    service: headless
spec:
  clusterIP: None
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app: project-forest